### ISSUE TITLE
Add skill_id and meta_skill_id to RobotState message. 

### ISSUE THREAD

**Issue by mohitsharma0690** [iamlab-cmu/robot-interface#26]
Right now we only have a skill description, there can be a weird edge case where the skill is repeated or the description is the same. To counter this we should also log the skill_id and meta_skill_id being executed. 

Also, these values should be logged on the C++ side and read by ROS's C++ end. Instead right now we read the skill description directly from shared memory which is not correct and can lead to bugs.

**Comment by firephinx** [comment]
They are now being published on a run loop process info ros publisher
